-- Opening hours backfill, generated by scripts/backfill-hours.mjs
-- Source: Google Places regularOpeningHours, via /api/place-details
-- 83 venues. Check the project ref is iguspxisuudvvlcbtaxk before running.
--
-- Only touches rows that still have no hours, so re-running is safe and it
-- will never overwrite hours someone has corrected by hand.

BEGIN;

UPDATE public.venues SET opening_hours = '{"mon":"10:00-19:00","tue":"10:00-19:00","wed":"10:00-19:00","thu":"10:00-19:00","fri":"10:00-19:00","sat":"10:00-19:00","sun":"10:00-19:00"}'::jsonb
  WHERE id = 1435 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Moco Museum London

UPDATE public.venues SET opening_hours = '{"mon":"09:00-21:00","tue":"09:00-21:00","wed":"09:00-21:00","thu":"09:00-21:00","fri":"09:00-21:00","sat":"09:00-21:00","sun":"09:00-19:30"}'::jsonb
  WHERE id = 1436 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Paradox Museum London

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:30","tue":"Closed","wed":"10:00-17:30","thu":"10:00-17:30","fri":"10:00-17:30","sat":"10:00-17:30","sun":"10:00-17:30"}'::jsonb
  WHERE id = 1437 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Leighton House

UPDATE public.venues SET opening_hours = '{"mon":"10:30-00:30","tue":"10:30-00:30","wed":"10:30-00:30","thu":"10:30-00:30","fri":"10:30-02:30","sat":"10:30-02:30","sun":"10:30-00:30"}'::jsonb
  WHERE id = 1741 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Rowans Tenpin Bowl

UPDATE public.venues SET opening_hours = '{"mon":"10:00-23:00","tue":"10:00-23:00","wed":"10:00-23:00","thu":"10:00-23:00","fri":"10:00-00:00","sat":"10:00-00:00","sun":"10:00-23:00"}'::jsonb
  WHERE id = 1742 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Queens Skate Dine Bowl

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1439 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Dulwich Picture Gallery

UPDATE public.venues SET opening_hours = '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-18:00","fri":"10:00-18:00","sat":"10:00-18:00","sun":"10:00-18:00"}'::jsonb
  WHERE id = 1440 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- The Courtauld Gallery

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1441 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Queen's House

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"Closed","thu":"Closed","fri":"11:00-18:00","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1442 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Royal Academy of Music Museum

UPDATE public.venues SET opening_hours = '{"mon":"08:30-18:00","tue":"08:30-18:00","wed":"08:30-18:00","thu":"08:30-18:00","fri":"08:30-18:00","sat":"10:00-18:00","sun":"Closed"}'::jsonb
  WHERE id = 1443 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Science Gallery London

UPDATE public.venues SET opening_hours = '{"mon":"11:00-00:00","tue":"11:00-00:00","wed":"11:00-00:00","thu":"11:00-00:00","fri":"11:00-01:00","sat":"11:00-01:00","sun":"11:00-00:00"}'::jsonb
  WHERE id = 1743 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Electric Shuffle

UPDATE public.venues SET opening_hours = '{"mon":"12:00-23:00","tue":"12:00-23:00","wed":"12:00-23:00","thu":"12:00-00:00","fri":"12:00-00:30","sat":"12:00-00:30","sun":"12:00-22:00"}'::jsonb
  WHERE id = 1744 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Roxy Ball Room

UPDATE public.venues SET opening_hours = '{"mon":"11:00-22:00","tue":"11:00-22:00","wed":"11:00-22:30","thu":"11:00-23:00","fri":"11:00-23:00","sat":"11:00-23:00","sun":"11:00-21:00"}'::jsonb
  WHERE id = 1745 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Puttshack

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"16:00-23:00","wed":"16:00-23:00","thu":"16:00-23:00","fri":"16:00-00:00","sat":"12:00-00:00","sun":"12:00-22:00"}'::jsonb
  WHERE id = 1746 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Junkyard Golf Club

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"12:00-18:00","thu":"12:00-18:00","fri":"12:00-18:00","sat":"12:00-18:00","sun":"12:00-18:00"}'::jsonb
  WHERE id = 1444 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Queer Britain Museum

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"10:00-16:30","wed":"10:00-16:30","thu":"10:00-16:00","fri":"10:00-16:30","sat":"10:00-16:30","sun":"10:00-16:30"}'::jsonb
  WHERE id = 1445 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- London Canal Museum

UPDATE public.venues SET opening_hours = '{"mon":"17:00-01:00","tue":"17:00-01:00","wed":"17:00-02:00","thu":"17:00-02:00","fri":"17:00-02:00","sat":"12:00-02:30","sun":"14:00-23:00"}'::jsonb
  WHERE id = 1748 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Lucky Voice Karaoke

UPDATE public.venues SET opening_hours = '{"mon":"10:30-15:30","tue":"Closed","wed":"Closed","thu":"Closed","fri":"10:30-15:30","sat":"10:30-15:30","sun":"10:30-15:30"}'::jsonb
  WHERE id = 1446 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Brunel Museum

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1447 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- London Museum Docklands

UPDATE public.venues SET opening_hours = '{"mon":"12:00-23:00","tue":"12:00-23:00","wed":"12:00-00:00","thu":"12:00-00:00","fri":"12:00-03:00","sat":"12:00-03:00","sun":"12:00-23:00"}'::jsonb
  WHERE id = 1749 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Bloomsbury Lanes

UPDATE public.venues SET opening_hours = '{"mon":"09:30-20:00","tue":"09:30-20:00","wed":"09:30-20:00","thu":"09:30-20:00","fri":"09:30-21:00","sat":"09:30-21:00","sun":"09:30-20:00"}'::jsonb
  WHERE id = 1452 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Twist Museum

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"12:00-23:00","wed":"12:00-23:00","thu":"12:00-23:00","fri":"12:00-23:00","sat":"10:00-23:00","sun":"10:00-22:00"}'::jsonb
  WHERE id = 1455 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Monopoly Lifesized

UPDATE public.venues SET opening_hours = '{"mon":"13:00-21:00","tue":"13:00-21:00","wed":"13:00-21:00","thu":"13:00-22:00","fri":"13:00-22:00","sat":"10:00-22:00","sun":"10:00-20:00"}'::jsonb
  WHERE id = 1456 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Immersive Gamebox Southbank

UPDATE public.venues SET opening_hours = '{"mon":"06:00-23:00","tue":"06:00-23:00","wed":"06:00-23:00","thu":"06:00-23:00","fri":"06:00-23:00","sat":"06:00-23:00","sun":"06:00-23:00"}'::jsonb
  WHERE id = 1750 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- London Aquatics Centre

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"Closed","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-18:00"}'::jsonb
  WHERE id = 1453 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Bubble Planet Experience London

UPDATE public.venues SET opening_hours = '{"mon":"06:30-22:00","tue":"06:30-22:00","wed":"06:30-22:00","thu":"06:30-22:00","fri":"06:30-22:00","sat":"08:00-20:00","sun":"08:00-20:00"}'::jsonb
  WHERE id = 1751 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Marshall Street Leisure Centre

UPDATE public.venues SET opening_hours = '{"mon":"06:30-22:00","tue":"06:30-22:00","wed":"06:30-22:00","thu":"06:30-22:00","fri":"06:30-22:00","sat":"09:30-18:00","sun":"09:30-18:00"}'::jsonb
  WHERE id = 1752 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Oasis Sports Centre

UPDATE public.venues SET opening_hours = '{"mon":"11:00-00:00","tue":"11:00-00:00","wed":"11:00-00:00","thu":"11:00-00:30","fri":"11:00-01:00","sat":"11:00-01:00","sun":"11:00-00:00"}'::jsonb
  WHERE id = 1458 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Flight Club Shoreditch

UPDATE public.venues SET opening_hours = '{"mon":"11:00-00:00","tue":"11:00-00:00","wed":"11:00-00:00","thu":"11:00-01:00","fri":"11:00-01:00","sat":"11:00-01:00","sun":"11:00-00:00"}'::jsonb
  WHERE id = 1459 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Flight Club Bloomsbury

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"18:00-01:00","thu":"18:00-02:00","fri":"18:00-03:00","sat":"14:00-03:00","sun":"17:00-00:00"}'::jsonb
  WHERE id = 1460 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Four Quarters Arcade Peckham

UPDATE public.venues SET opening_hours = '{"mon":"16:00-22:00","tue":"16:00-23:00","wed":"16:00-23:00","thu":"16:00-23:00","fri":"13:00-00:00","sat":"12:00-00:00","sun":"12:00-22:00"}'::jsonb
  WHERE id = 1461 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Four Quarters Arcade Elephant Park

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"11:30-00:00","wed":"11:30-00:00","thu":"11:30-00:00","fri":"11:30-01:00","sat":"10:30-01:00","sun":"11:30-00:00"}'::jsonb
  WHERE id = 1462 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Fairgame Canary Wharf

UPDATE public.venues SET opening_hours = '{"mon":"11:30-23:30","tue":"11:30-23:30","wed":"11:30-00:00","thu":"11:30-00:30","fri":"11:30-01:00","sat":"10:00-01:00","sun":"11:30-22:30"}'::jsonb
  WHERE id = 1463 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Boom Battle Bar Oxford Street

UPDATE public.venues SET opening_hours = '{"mon":"17:00-00:00","tue":"17:00-00:00","wed":"17:00-00:00","thu":"17:00-02:00","fri":"15:00-02:00","sat":"13:00-02:00","sun":"15:00-00:00"}'::jsonb
  WHERE id = 1465 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Mr Fogg's Society of Exploration

UPDATE public.venues SET opening_hours = '{"mon":"13:00-21:00","tue":"13:00-21:00","wed":"13:00-21:00","thu":"13:00-21:00","fri":"13:00-21:00","sat":"09:00-21:00","sun":"09:00-21:00"}'::jsonb
  WHERE id = 1466 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- The Crystal Maze LIVE Experience London

UPDATE public.venues SET opening_hours = '{"mon":"10:00-23:00","tue":"10:00-23:00","wed":"10:00-23:00","thu":"10:00-23:00","fri":"10:00-23:00","sat":"10:00-23:00","sun":"10:00-22:00"}'::jsonb
  WHERE id = 1467 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- F1 Arcade London

UPDATE public.venues SET opening_hours = '{"mon":"10:00-21:30","tue":"10:00-21:30","wed":"10:00-21:30","thu":"10:00-21:30","fri":"10:00-21:30","sat":"10:00-21:30","sun":"10:00-21:00"}'::jsonb
  WHERE id = 1468 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Picturehouse Central

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1471 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Museum of the Home

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1754 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Discover Children's Story Centre

UPDATE public.venues SET opening_hours = '{"mon":"10:00-00:00","tue":"10:00-00:00","wed":"10:00-00:00","thu":"10:00-00:00","fri":"10:00-00:00","sat":"10:00-00:00","sun":"12:00-23:30"}'::jsonb
  WHERE id = 1469 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Curzon Soho

UPDATE public.venues SET opening_hours = '{"mon":"13:00-23:00","tue":"13:00-23:00","wed":"13:00-23:00","thu":"13:00-00:00","fri":"12:00-00:00","sat":"12:00-00:00","sun":"13:00-23:00"}'::jsonb
  WHERE id = 1464 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Boom Battle Bar Aldgate

UPDATE public.venues SET opening_hours = '{"mon":"09:00-19:00","tue":"09:00-19:00","wed":"09:00-19:00","thu":"09:00-19:00","fri":"09:00-19:00","sat":"09:00-19:00","sun":"09:00-19:00"}'::jsonb
  WHERE id = 1755 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Bread Ahead Bakery School

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1438 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Bank of England Museum

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"11:00-18:00","thu":"12:00-19:00","fri":"12:00-19:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1756 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Lady Dinah's Cat Emporium

UPDATE public.venues SET opening_hours = '{"mon":"18:00-23:00","tue":"18:00-23:00","wed":"18:00-23:30","thu":"18:00-00:00","fri":"18:00-00:00","sat":"18:00-00:00","sun":"18:00-23:00"}'::jsonb
  WHERE id = 1757 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Backyard Comedy Club

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"Closed","wed":"Closed","thu":"Closed","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1758 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Peter Harrison Planetarium

UPDATE public.venues SET opening_hours = '{"mon":"17:00-23:00","tue":"17:00-23:00","wed":"17:00-23:00","thu":"17:00-23:00","fri":"17:00-23:00","sat":"17:00-23:00","sun":"Closed"}'::jsonb
  WHERE id = 1759 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Wilton's Music Hall

UPDATE public.venues SET opening_hours = '{"mon":"11:00-15:30","tue":"12:00-16:00","wed":"11:00-16:00","thu":"11:00-16:00","fri":"11:00-19:00","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1760 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Beefeater Gin Distillery

UPDATE public.venues SET opening_hours = '{"mon":"09:00-18:00","tue":"09:00-18:00","wed":"09:00-18:00","thu":"09:00-18:00","fri":"09:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1761 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Sipsmith Distillery

UPDATE public.venues SET opening_hours = '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-22:00","fri":"10:00-18:00","sat":"10:00-22:00","sun":"10:00-18:00"}'::jsonb
  WHERE id = 1704 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- V&A East Storehouse

UPDATE public.venues SET opening_hours = '{"mon":"10:00-20:00","tue":"10:00-20:00","wed":"10:00-20:00","thu":"10:00-20:00","fri":"10:00-21:00","sat":"10:00-21:00","sun":"10:00-20:00"}'::jsonb
  WHERE id = 1705 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Museum of Illusions London

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"Closed","thu":"Closed","fri":"Closed","sat":"12:00-17:00","sun":"12:00-17:00"}'::jsonb
  WHERE id = 1707 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Barbican Conservatory

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"Closed","thu":"Closed","fri":"12:00-15:15","sat":"12:00-15:15","sun":"12:00-15:15"}'::jsonb
  WHERE id = 1709 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Dennis Severs' House

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"10:30-16:30","wed":"10:30-16:30","thu":"10:30-16:30","fri":"10:30-16:30","sat":"10:30-16:30","sun":"Closed"}'::jsonb
  WHERE id = 1710 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- The Charterhouse

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1711 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Handel Hendrix House

UPDATE public.venues SET opening_hours = '{"mon":"10:30-17:00","tue":"Closed","wed":"10:30-17:00","thu":"10:30-17:00","fri":"10:30-17:00","sat":"10:30-17:00","sun":"10:30-17:00"}'::jsonb
  WHERE id = 1712 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Freud Museum London

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"11:00-17:00"}'::jsonb
  WHERE id = 1713 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Foundling Museum

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1714 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Garden Museum

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"11:00-16:30","wed":"11:00-16:30","thu":"11:00-16:30","fri":"11:00-16:30","sat":"11:00-16:30","sun":"Closed"}'::jsonb
  WHERE id = 1715 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- The Fan Museum

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1716 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Eltham Palace

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:30","tue":"10:00-17:30","wed":"10:00-17:30","thu":"10:00-17:30","fri":"10:00-17:30","sat":"10:00-17:30","sun":"10:00-17:30"}'::jsonb
  WHERE id = 1717 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Horniman Museum

UPDATE public.venues SET opening_hours = '{"mon":"09:00-20:00","tue":"09:00-20:00","wed":"10:00-20:00","thu":"09:00-20:00","fri":"09:00-20:00","sat":"10:00-17:00","sun":"12:00-16:00"}'::jsonb
  WHERE id = 1718 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Peckham Library

UPDATE public.venues SET opening_hours = '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-20:00","fri":"Closed","sat":"09:00-17:00","sun":"Closed"}'::jsonb
  WHERE id = 1719 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Bethnal Green Library

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"12:00-18:00","wed":"12:00-20:00","thu":"12:00-20:00","fri":"12:00-20:00","sat":"12:00-20:00","sun":"12:00-20:00"}'::jsonb
  WHERE id = 1720 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- National Poetry Library

UPDATE public.venues SET opening_hours = '{"mon":"10:00-16:00","tue":"10:00-16:00","wed":"10:00-16:00","thu":"10:00-16:00","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1721 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Guildhall Library

UPDATE public.venues SET opening_hours = '{"mon":"09:00-01:00","tue":"09:00-01:00","wed":"09:00-01:00","thu":"09:00-01:00","fri":"09:00-01:00","sat":"09:00-01:00","sun":"09:00-01:00"}'::jsonb
  WHERE id = 1722 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Maughan Library

UPDATE public.venues SET opening_hours = '{"mon":"11:00-17:00","tue":"11:00-17:00","wed":"11:00-17:00","thu":"11:00-17:00","fri":"11:00-17:00","sat":"11:00-17:00","sun":"11:00-17:00"}'::jsonb
  WHERE id = 1724 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Alexandra Palace Ice Rink

UPDATE public.venues SET opening_hours = '{"mon":"08:00-22:00","tue":"08:00-22:00","wed":"08:00-22:00","thu":"08:00-22:00","fri":"08:00-22:00","sat":"09:00-20:00","sun":"09:00-20:00"}'::jsonb
  WHERE id = 1725 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- The Castle Climbing Centre

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"11:00-18:00","thu":"11:00-18:00","fri":"11:00-18:00","sat":"11:00-18:00","sun":"11:00-18:00"}'::jsonb
  WHERE id = 1726 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Camden Arts Centre

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"10:00-16:00","thu":"10:00-16:00","fri":"10:00-16:00","sat":"Closed","sun":"10:00-16:00"}'::jsonb
  WHERE id = 1727 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Burgh House & Hampstead Museum

-- Keats House: wed: multiple ranges, kept the first: 11:00 AM – 1:00 PM, 2:00 – 5:00 PM; thu: multiple ranges, kept the first: 11:00 AM – 1:00 PM, 2:00 – 5:00 PM; fri: multiple ranges, kept the first: 11:00 AM – 1:00 PM, 2:00 – 5:00 PM; sun: multiple ranges, kept the first: 11:00 AM – 1:00 PM, 2:00 – 5:00 PM
UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"11:00-13:00","thu":"11:00-13:00","fri":"11:00-13:00","sat":"Closed","sun":"11:00-13:00"}'::jsonb
  WHERE id = 1728 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Keats House

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"Closed","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"Closed"}'::jsonb
  WHERE id = 1729 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Islington Museum

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"10:00-22:00","wed":"10:00-22:00","thu":"10:00-22:00","fri":"10:00-20:00","sat":"10:00-20:00","sun":"10:00-20:00"}'::jsonb
  WHERE id = 1730 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Turning Earth

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"10:00-17:00","sun":"11:00-17:00"}'::jsonb
  WHERE id = 1731 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- London Glassblowing

UPDATE public.venues SET opening_hours = '{"mon":"06:30-21:30","tue":"06:30-21:30","wed":"06:30-21:30","thu":"06:30-21:30","fri":"06:30-21:30","sat":"09:00-18:00","sun":"09:00-18:00"}'::jsonb
  WHERE id = 1732 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Ironmonger Row Baths

UPDATE public.venues SET opening_hours = '{"mon":"10:00-21:30","tue":"10:00-21:30","wed":"10:00-21:30","thu":"10:00-21:30","fri":"10:00-21:30","sat":"10:00-20:00","sun":"10:00-20:00"}'::jsonb
  WHERE id = 1733 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Porchester Spa

UPDATE public.venues SET opening_hours = '{"mon":"06:00-23:00","tue":"06:00-23:00","wed":"06:00-23:00","thu":"06:00-23:00","fri":"06:00-23:00","sat":"08:00-22:00","sun":"08:00-22:00"}'::jsonb
  WHERE id = 1734 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- VauxWall Climbing

UPDATE public.venues SET opening_hours = '{"mon":"09:00-17:00","tue":"09:00-17:00","wed":"09:00-17:00","thu":"09:00-17:00","fri":"09:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1735 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Royal Institution

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"13:00-17:00","wed":"13:00-17:00","thu":"13:00-17:00","fri":"13:00-17:00","sat":"11:00-17:00","sun":"Closed"}'::jsonb
  WHERE id = 1736 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Petrie Museum of Egyptian Archaeology

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"10:00-17:00","fri":"10:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb
  WHERE id = 1737 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Wiener Holocaust Library

UPDATE public.venues SET opening_hours = '{"mon":"Closed","tue":"Closed","wed":"Closed","thu":"Closed","fri":"10:00-16:00","sat":"10:00-16:00","sun":"10:00-16:00"}'::jsonb
  WHERE id = 1738 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Musical Museum

UPDATE public.venues SET opening_hours = '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-22:00","fri":"10:00-18:00","sat":"10:00-22:00","sun":"10:00-18:00"}'::jsonb
  WHERE id = 1739 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- V&A East Museum

UPDATE public.venues SET opening_hours = '{"mon":"10:00-17:00","tue":"10:00-17:00","wed":"10:00-17:00","thu":"Closed","fri":"10:00-17:00","sat":"09:00-18:00","sun":"10:00-17:00"}'::jsonb
  WHERE id = 1740 AND (opening_hours IS NULL OR opening_hours = '{}'::jsonb);  -- Mundo Pixar

COMMIT;

-- Needs a human eye, Places returned a differently named place:
--   Royal Opera House Tour  ->  Places returned "Royal Ballet and Opera"
--   Swingers City  ->  Places returned "Swingers West End"
--   Everyman Cinema King's Cross  ->  Places returned "Everyman Kings Cross"
--   London Film Museum  ->  Places returned "The Cinema Museum"
--   ABBA Voyage  ->  Places returned "ABBA Arena"

-- No hours available:
--   Whistle Punks Urban Axe Throwing  (Places has no hours for it)
--   Royal Albert Hall Tour  (Places has no hours for it)
--   Shakespeare's Globe Exhibition  (Places has no hours for it)
--   Van Gogh: The Immersive Experience London  (Places has no hours for it)
--   Clip 'n Climb Chelsea  (Places has no hours for it)
--   The Cinema Museum  (Places has no hours for it)
--   Black Cultural Archives  (Places has no hours for it)
--   Wake The Tiger  (no Places match)
--   Two Temple Place  (Places has no hours for it)
--   Alexandra Palace  (Places has no hours for it)